name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate custom snake
        uses: Platane/snk@v3
        with:
          github_user_name: moses15glx
          outputs: dist/snake.svg

          # ðŸ”¥ PersonalizaÃ§Ã£o:
          color_snake: "#00A2FF"        # Cobrinha azul
          color_path: "#005C99"         # Rastro azul escuro
          color_dots: "#00FF00"         # Commits verdes
          color_back: "#000000"         # Fundo preto
          hide_progress_bar: true       # Remove barra de progresso

      - name: Push snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Update custom snake"
